export { getCurrentInstance } from './component'
export { h } from './h'
export { createTextVNode }  from './vnode'
export { renderSlots } from './helpers/renderSlots'
export { provide, inject } from './apiInject'
export { createRenderer } from './renderer'
export { nextTick } from './scheduler'
export * from '../reactivity'