export { getCurrentInstance } from './component'
export { h, createTextVNode } from './h'
export { renderSlots } from './helpers/renderSlots'
export { provide, inject } from './apiInject'
export { createRenderer } from './renderer'
export * from '../reactivity'